In [2]:
!pip install tqdm

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [77]:
from collections import defaultdict, deque, Counter
import numpy as np
from tqdm import tqdm_notebook as tqdm 
import pandas as pd
from heapq import nlargest

#from sklearn.preprocessing import normalize

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [5]:
filename = "cheetah.cs.fiu.edu-110108-113008.1.blkparse"
df = pd.read_csv(filename, sep=' ',header = None)
df.columns = ['timestamp','pid','pname','blockNo', \
              'blockSize', 'readOrWrite', 'bdMajor', 'bdMinor', 'hash']
blocktrace = df['blockNo'].tolist()
len(blocktrace)

1322890

In [49]:
def potential_eviction(Cache, upcoming_index, N):
    index = upcoming_index.keys()
    topN = nlargest(N, index)
    evictionBlock = [upcoming_index[i] for i in topN]
    evictionIndex = [list(Cache).index(i) for i in evictionBlock]
    eviction = np.zeros(len(Cache), dtype=int)
    eviction[evictionIndex] = 1
    return eviction

In [79]:
def belady_opt(blocktrace, frame):
    '''
    INPUT
    ==========
    blocktrace = list of block request sequence
    frame = size of the cache
    
    OUTPUT
    ==========
    hitrate 
    '''
    infinite_index = 100 * len(blocktrace) 
    # should be a large integer
    
    block_index = defaultdict(deque) 
    # dictionary with block number as key and list
    # of index value in blocktrace
    
    upcoming_index = defaultdict(int)
    # dictionary with index number as key and value as block
    
    frequency = defaultdict(int)
    # dictionary of block as key and number
    # of times it's been requested so far
    
    recency = list()
    # list of block in order of their request
    
    Cache = set()
    # Cache with block
    
    dataset = np.array([], dtype=int).reshape(0,4)
    
    hit, miss = 0, 0
    
    # populate the block_index
    for i, block in enumerate(tqdm(blocktrace, \
                              desc="buidling index", leave=False)):
        block_index[block].append(i)
        
    # sequential block requests start
    for i, block in enumerate(tqdm(blocktrace, desc="sequence", leave=False)):
        
        # increament the frequency number for the block
        frequency[block] += 1
        
        # make sure block has the value in block_index dictionary 
        # as current seq_number
        if len(block_index[block]) != 0 and block_index[block][0] == i:
            
            # if yes, remove the first element of block_index[block]
            block_index[block].popleft()
        
        # if block exist in current cache
        if block in Cache:
            
            # increment hit
            hit += 1
            
            # update the recency
            recency.remove(block)
            recency.append(block)
            
            # update upcoming_index
            if i in upcoming_index:
                
                # delete old index
                del upcoming_index[i]
        
                if len(block_index[block]) is not 0:
                    # add new upcoming index
                    upcoming_index[block_index[block][0]] = block
                    # remove index from block_index
                    block_index[block].popleft()
                else:
                    # add a large integer as index
                    upcoming_index[infinite_index] = block
                    # increament large integer
                    infinite_index+=1
           
        # block not in current cache
        else:
            
            # increament miss
            miss += 1
            
            # if cache has no free space
            if len(Cache) == frame:
                
                
                blockNo = np.array([i for i in Cache], dtype=int)
                normBlock = blockNo / np.linalg.norm(blockNo)
                recency_ = np.array([recency.index(i) for i in Cache], dtype=int)
                normRecent = recency_ / np.linalg.norm(recency_)
                frequency_ = np.array([frequency[i] for i in Cache], dtype=int)
                Normfrequent = frequency_ / np.linalg.norm(frequency_)
                eviction_ = potential_eviction(Cache, upcoming_index, 100)
                stack = np.column_stack((normBlock, normRecent, Normfrequent, eviction_))
                    
                # evict the farthest block in future request from cache
                if len(upcoming_index) != 0:
                    
                    # find the farthest i.e. max_index in upcoming_index
                    max_index = max(upcoming_index)
                    
                    # remove the block with max_index from cache
                    Cache.remove(upcoming_index[max_index])
                    
                    # remove the block with max_index from recency dict
                    recency.remove(upcoming_index[max_index])
                    
                    # remove max_index element from upcoming_index
                    del upcoming_index[max_index]
                    
            # add upcoming request of current block in upcoming_index
            if len(block_index[block]) != 0:
                
                # add upcoming index of block
                upcoming_index[block_index[block][0]] = block
               
                # remove the index from block_index 
                block_index[block].popleft()
            
            else:
                
                # add a large integer as index
                upcoming_index[infinite_index] = block
                
                # increament high number
                infinite_index += 1
                
            
            if len(Cache) == frame:
                dataset = np.vstack((dataset, stack))
            # add block into Cache
            Cache.add(block)
            
            # add block into recency
            recency.append(block)
            
            
    # calculate hitrate
    hitrate = hit / (hit + miss)

    return hitrate, dataset

In [80]:
hitrate, dataset = belady_opt(blocktrace, 500)

KeyboardInterrupt: 

In [64]:
dataset

array([[0.04372909, 0.00605093, 0.04509494, 0.        ],
       [0.04372941, 0.04592502, 0.04509494, 0.        ],
       [0.04372909, 0.00620608, 0.04509494, 0.        ],
       ...,
       [0.04521704, 0.01070549, 0.04748762, 0.        ],
       [0.04359734, 0.06656024, 0.04748762, 1.        ],
       [0.04521738, 0.05057958, 0.03957302, 0.        ]])

In [65]:
X_train, X_test, Y_train, Y_test = train_test_split(dataset[:,:3], dataset[:,-1].astype(int) ,test_size=0.3, random_state=0, shuffle=False)

In [78]:
#Fitting Logistic Regression Model
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)

Y_pred = logreg.predict(X_test)

print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, Y_test)))

confusion_matrix = confusion_matrix(Y_test,Y_pred)
print (confusion_matrix)


Accuracy of logistic regression classifier on test set: 0.90
[[143465   7001]
 [ 10869  26765]]


In [74]:
type(Y_test)

numpy.ndarray

In [75]:
type(Y_pred)

numpy.ndarray

In [72]:
 dataset[:,-1].astype(int)

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
def belady_opt_with_lr(blocktrace, frame):
    '''
    INPUT
    ==========
    blocktrace = list of block request sequence
    frame = size of the cache
    
    OUTPUT
    ==========
    hitrate 
    '''
    infinite_index = 100 * len(blocktrace) 
    # should be a large integer
    
    block_index = defaultdict(deque) 
    # dictionary with block number as key and list
    # of index value in blocktrace
    
    upcoming_index = defaultdict(int)
    # dictionary with index number as key and value as block
    
    frequency = defaultdict(int)
    # dictionary of block as key and number
    # of times it's been requested so far
    
    recency = list()
    # list of block in order of their request
    
    Cache = set()
    # Cache with block
    
    #dataset = np.array([], dtype=int).reshape(0,4)
    
    hit, miss = 0, 0
    
    # populate the block_index
    for i, block in enumerate(tqdm(blocktrace, \
                              desc="buidling index", leave=False)):
        block_index[block].append(i)
        
    # sequential block requests start
    for i, block in enumerate(tqdm(blocktrace, desc="sequence", leave=False)):
        
        # increament the frequency number for the block
        frequency[block] += 1
        
        # make sure block has the value in block_index dictionary 
        # as current seq_number
        if len(block_index[block]) != 0 and block_index[block][0] == i:
            
            # if yes, remove the first element of block_index[block]
            block_index[block].popleft()
        
        # if block exist in current cache
        if block in Cache:
            
            # increment hit
            hit += 1
            
            # update the recency
            recency.remove(block)
            recency.append(block)
            
            # update upcoming_index
            if i in upcoming_index:
                
                # delete old index
                del upcoming_index[i]
        
                if len(block_index[block]) is not 0:
                    # add new upcoming index
                    upcoming_index[block_index[block][0]] = block
                    # remove index from block_index
                    block_index[block].popleft()
                else:
                    # add a large integer as index
                    upcoming_index[infinite_index] = block
                    # increament large integer
                    infinite_index+=1
           
        # block not in current cache
        else:
            
            # increament miss
            miss += 1
            
            # if cache has no free space
            if len(Cache) == frame:
                
                
                blockNo = np.array([i for i in Cache], dtype=int)
                normBlock = blockNo / np.linalg.norm(blockNo)
                recency_ = np.array([recency.index(i) for i in Cache], dtype=int)
                normRecent = recency_ / np.linalg.norm(recency_)
                frequency_ = np.array([frequency[i] for i in Cache], dtype=int)
                Normfrequent = frequency_ / np.linalg.norm(frequency_)
                #eviction_ = potential_eviction(Cache, upcoming_index, 100)
                stack = np.column_stack((normBlock, normRecent, Normfrequent))
                    
                # evict the farthest block in future request from cache
                if len(upcoming_index) != 0:
                    
                    # find the farthest i.e. max_index in upcoming_index
                    max_index = max()
                    
                    # remove the block with max_index from cache
                    Cache.remove(upcoming_index[max_index])
                    
                    # remove the block with max_index from recency dict
                    recency.remove(upcoming_index[max_index])
                    
                    # remove max_index element from upcoming_index
                    del upcoming_index[max_index]
                    
            # add upcoming request of current block in upcoming_index
            if len(block_index[block]) != 0:
                
                # add upcoming index of block
                upcoming_index[block_index[block][0]] = block
               
                # remove the index from block_index 
                block_index[block].popleft()
            
            else:
                
                # add a large integer as index
                upcoming_index[infinite_index] = block
                
                # increament high number
                infinite_index += 1
                
            
            #if len(Cache) == frame:
            #    dataset = np.vstack((dataset, stack))
            # add block into Cache
            Cache.add(block)
            
            # add block into recency
            recency.append(block)
            
            
    # calculate hitrate
    hitrate = hit / (hit + miss)

    return hitrate, dataset

In [82]:
any([1,2,3,4,5])

True